# ArtFight Atom Service Configuration

# General settings
request_interval_sec = 300  # Minimum seconds between requests to ArtFight (5 minutes)
team_check_interval_sec = 300  # How often to check team standings (30 minutes)
battle_over_detection = false  # Stop team checks after 3 consecutive 'battle over' detections

# ArtFight settings
artfight_base_url = "https://artfight.net"

# Authentication settings
laravel_session = ""
cf_clearance = ""
remember_web = ""

# Server settings
host = "0.0.0.0"
port = 8000
debug = false

# Atom feed settings
max_users_per_feed = 5  # Maximum number of users allowed in a single multiuser feed
max_feed_items = 50     # Maximum number of items returned in a feed

# Whitelist of supported ArtFight profiles (optional)
# If empty, all profiles are allowed
whitelist = [
    "example_user"
]

# Discord Bot Configuration
discord_enabled = false  # Set to true to enable Discord bot functionality
discord_token = ""       # Discord bot token (required for bot mode)
discord_guild_id = 0     # Discord guild (server) ID for bot commands (optional)
discord_channel_id = 0   # Discord channel ID for notifications (optional)
discord_webhook_url = "" # Discord webhook URL for notifications (alternative to bot)

# Discord notification settings
discord_notify_attacks = true      # Send notifications for new attacks
discord_notify_defenses = true     # Send notifications for new defenses
discord_notify_team_changes = true # Send notifications for team standing changes
discord_notify_leader_changes = true # Send notifications for leader changes
discord_include_team_balance_plot = true # Include team balance subplot (user counts and differences) in Discord charts
discord_startup_timeout = 120      # Discord bot startup timeout in seconds (increase for remote servers)

# User monitoring configuration
monitor_list = [
    "example_user"
]

[teams]
team1 = { name = "Fossils", color = "#BA8C25", image_url = "https://images.artfight.net/2025/2025_Fossils.png" }
team2 = { name = "Crystals", color = "#D35E88", image_url = "https://images.artfight.net/2025/2025_Crystals.png" }
