# ArtFight RSS Service Configuration

# General settings
request_interval_sec = 300  # Minimum seconds between requests to ArtFight (5 minutes)
team_check_interval_sec = 300  # How often to check team standings (30 minutes)

# ArtFight settings
artfight_base_url = "https://artfight.net"

# Authentication settings
laravel_session = ""
cf_clearance = ""
remember_web = ""

# Server settings
host = "0.0.0.0"
port = 8000
debug = false

# Whitelist of supported ArtFight profiles (optional)
# If empty, all profiles are allowed
whitelist = [
    "example_user"
]

[teams]
team1 = { name = "Fossils", color = "#BA8C25", image_url = "https://images.artfight.net/2025/2025_Fossils.png" }
team2 = { name = "Crystals", color = "#D35E88", image_url = "https://images.artfight.net/2025/2025_Crystals.png" }
