version: '3.8'

services:
  artfight-rss:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./.env:/app/.env:ro
      - ./cache:/app/cache
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 